package by.btslogistics.fklservice.dao.model.flk.constants;

public interface FlkNamesProcAndPkg {

    String GET_LIST_ERRORS_FOR_SERVICE = "getListErrorsForService";
    String GET_LIST_ERRORS_FOR_UI = "getListErrorsForUi";
    String GET_LIST_FLK_CHECKS_FOR_UI = "getListFlkChecksForUi";

    String VALIDATE_SD_START_VALIDATE = "TTS_FORMAT_LOGICAL_CONTROL.VALIDATE_SD.START_VALIDATE";
    String VALIDATE_SD_ERRORS_FLK_LOG_FOR_UI = "TTS_FORMAT_LOGICAL_CONTROL.VALIDATE_SD.ERRORS_FLK_LOG_FOR_UI";
    String VALIDATE_SD_LIST_FLK_CHECKS_FOR_UI = "TTS_FORMAT_LOGICAL_CONTROL.VALIDATE_SD.LIST_FLK_CHECKS_FOR_UI";

}
